### ISSUE TITLE
Compiling on Linux?

### ISSUE THREAD

**Issue by soup6020** [doadam/ziVA#3]
I attempt to build this on Linux, but get this output:

Creating directories
Beginning release build
Compiling: utils.m -> build/release/utils.o
g++: error: arm64-apple-darwin9: No such file or directory
g++: error: unrecognized command line option ‘-target’
make[1]: *** [build/release/utils.o] Error 1
make: *** [release] Error 2

I'm probably the one in the wrong here, any advice?

**Comment by MrARM** [comment]
You don't have the iOS SDK. It would require a bit of work to get that working because mac has it built in. you just need to install xcode to activate it.

**Comment by jmukes97** [comment]
@MrARM You cant actually install Xcode on any linux machine. You can find a mac and download the SDK for ios 10 though.

**Comment by superE03** [comment]
Closed because I found the iOS SDK.
